### ISSUE TITLE
Problems with shader with #includes

### ISSUE THREAD

**Issue by KakCAT** [procfxgen/MGShaderEditor#1]
hi!

I'm having a problem with shaders that have #include in it. The error which appears is:

14:45:02 Value cannot be null.
14:45:02 Parameter name: path
14:45:02 Failed to parse !

It seems a path misconfiguration, passing the _strFileName to DoBuild and then using _strFileName instead of "\" seems to fix the problem, although I'm not sure because I'm having another problem compiled the shader I'm trying. (this "patch" only works when loading the shader via menu option, not when pressing F5)

To reproduce, just add 

include "macros/test.fx" 

to the SimpleColor.fx example

**Comment by fxgenstudio** [comment]
It's fixed in V1.5
Thanks.
